### ISSUE TITLE
'/tmp/plugins/snapserver.zip' is not a directory

### ISSUE THREAD

**Issue by diegoamloiola** [Saiyato/volumio-snapserver-plugin#18]
* After running the command `volumio plugin install` it returns this error
Could you help me with the following error?

 Do you want to install this plugin anyway? Yes
Compressing the plugin
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (pt_BR.UTF-8)
Plugin succesfully compressed
/bin/mv: target '/tmp/plugins/snapserver.zip' is not a directory
(node:2504) UnhandledPromiseRejectionWarning: Error: Command failed: /bin/mv *.zip /tmp/plugins/snapserver.zip
/bin/mv: target '/tmp/plugins/snapserver.zip' is not a directory

    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at /volumio/pluginhelper.js:778:17
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2504) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2504) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kramer65** [comment]
I just had this exact same problem. The problem for me turned out to be that I first put the source code of this plugin in `~/plugins/` and then tried to install from there. When I put the folder of this plugin in my home folder (`/home/volumio/`) I could install it without errors.

It doesn't work for me yet, but I think that's a different problem.
